---
# Add group and user
- name: Add group called 1stack
  group:
    name: 1stack
    gid: 2397
    state: present

- name: Add user and append to group
  user:
    name: otvault
    comment: OT vault user
    uid: 29938
    group: 1stack
    expires: -1

- name: set a passwd to otvault user
  user: 
    name: otvault
    password: "{{ 'admin123' | password_hash('sha512') }}" 
#    update_password: on_create   

- name: change password policies and set password
  shell: |
    chage -I -1 -m 0 -M 99999 -E -1 otvault
  register: shell_output

#vars:
    # NOTICE!!!:
    # DO NOT PUT PLAIN TEXT PASSWORDS HERE!
    # use encrypted passwords or put them in Ansible vault
    # but this is just a demo
#    vaulted_password: mySecret.

#- name: Add user  with a password
#      user:
#        name: user
#        password: "{{ vaulted_password | password_hash('sha512') }}"
#        update_password: on_create