---
- hosts: all
  gather_facts: yes # Gather facts from all hosts
  tasks:
    - name: "Collect facts from reachable hosts"
      ping:
      register: ping_result # Register the result of the ping task

    - name: "Gather Host Name"
      shell: echo $HOSTNAME
      register: host_name
    
    - name: "Display OS infos of reachable hosts"
      debug:
        msg: "OS family: {{ ansible_os_family }} {{ ansible_distribution_major_version }} {{ ansible_distribution_release }} {{ ansible_distribution_version }}"
      when: ping_result.ping == "pong" # only display facts for reachable hosts

    - name: "Read a file content"
      shell: |
        cat /etc/resolv.conf
      register: resolv_result # Register the result of cat task
    - debug: msg="{{ resolv_result.stdout }}"

#    - name: "Display resolv.conf"
#      debug:
#        var: resolv_result.stdout_lines

    - name: "Copy the DNS information to a Local File"
      lineinfile:
        line: "{{ host_name.stdout }} , {{ ansible_distribution_release }} , {{ ansible_distribution_version }} , {{ resolv_result.stdout }}"
        dest: "/tmp/DNS_Details.{{ file_format }}"
        create: true
      delegate_to: localhost 

    - name: "Sending Email"
      mail:
        attach: "/tmp/DNS_Details.{{ file_format }}"
        body: 'Please find the attached Hosts Details .'
        from: "{{ from_email_id }}"
        host: localhost
        subject: 'DNS Config'
        to: "{{ to_email_id }}"
      run_once: true
      delegate_to: localhost 

    - name: "Delete the Temporary File"
      shell: |
        yes | rm /tmp/DNS_Details.{{ file_format }}
      delegate_to: localhost
      run_once: true
    
    